### ISSUE TITLE
QoL Improvement Suggestion: Allow Home & End keys to jump to the top & bottom of the Game List

### ISSUE THREAD

**Issue by gdinit** [benini/scid#136]
Hi,

**Suggestion:**
As per title, just a QoL Improvement Suggestion... Allow **Home** & **End** keys to **jump to the top** & **bottom** of the Game List

**Justification:**
As you know, in many applications, the Home key is bound to "go to top" function and likewise the End key is bound to "go to bottom (end) (of list)" function. 
I was thinking it would be a good QoL improvement to get this implemented.

Thank you

**Comment by benini** [comment]
There are keyboard shortcuts thata are used to navigate the game. Like <left arrow> (previous move), <right arrow> (next move),  <home> (beginning of the variation) and <end> (end of the game).
I prefer to associate those keyboard shortcuts with their respective functions independently of the currently focused windows whenever possible.

**Comment by gdinit** [comment]
> There are keyboard shortcuts thata are used to navigate the game. Like (previous move), (next move), (beginning of the variation) and (end of the game). 

Yes, I use them, and they are excellent, where they exist!
However in this instance, on my mind, there is a perceived "lack of keyboard shortcut(s)" to do certain things, such as: 
"(in the Game List) window/pane, jump to the bottom of the game list (or jump to top)".
Sometimes it is a lot of "PageUp/PageDown" keys to scroll around and a single JUMP would be best.
Yes, I am aware, we of course could also use other functions to filter around but sometimes just jumping to top (or bottom) is the most natural action (at least for me).
Currently, the only reasonable way to jump huge distances (or to top/bottom of the list) is using the mouse.

You mention that Home & End keys are already bound to actions within the currently loaded game (jump to the first and last move of the game). Those keybindings is something I use too and would not want to lose that.
I did not mention this "CTRL" modifier bit in my previous message, clearly I did not think on my suggestion adequately...
But now that I read your response, I thought about it a little more.
Perhaps you could consider leaving Home & End intact but also adding new functionality via CTRL+Home and CTRL+End keybindings?

I understand the issue is already CLOSED so this is just my last attempt to see if I can get you on board with this idea.
If not, no problem.

Either way, thank you for all your hard work, it is much appreciated as I use SCID daily!

**Comment by gdinit** [comment]
Forgot to tag you @benini (just in case you do not spot my update otherwise). Thanks.
