### ISSUE TITLE
Performance error

### ISSUE THREAD

**Issue by tritcma** [benini/scid#166]
Received a cryptic error message (attached) while annotating a game. Can you please advise or recommend a fix?
![Screenshot 2024-02-01](https://github.com/benini/scid/assets/126005769/2e0d1c42-c209-4022-b312-7752e73cc69f)

**Comment by benini** [comment]
I don't know. I did a quick grep in the analysis.tcl file for "performance" or "messageBox," but I didn't find anything.
In any case, when the function is reimplemented with the new engine interface, all the old code (and this error) will be removed.
