### ISSUE TITLE
Misplaced scrolling widgets

### ISSUE THREAD

**Issue by whatteaux** [benini/scid#182]
On some panels (SCID 5.0.2 Feb 8 2024), there is a list of names (Matches) to choose from.  If the list is too long to fit its area, a scroll bar ought to appear in the area (like it does in the game list).  However, in the "Name Editor" panel, for example, if there are too many names for the "Matches" area, a pair of scroll-bar arrows appears above and below the "Replace:" text label (!) instead of in the Matches area.  Likewise in the "Save: Replace Game..." panel, the scroll arrows belonging to the Matches area, appear above and below the Event entry field instead.  I've seen this happen with other list fields (e.g. the "Round:" field in the same Save... dialogue) also.
![SCID1](https://github.com/benini/scid/assets/167518035/e6fdf452-87fd-4267-9433-4614061c8dcf)
![SCID2](https://github.com/benini/scid/assets/167518035/c833f2f4-d3bb-427e-8d8e-908f004d8cee)

**Comment by benini** [comment]
Use https://sourceforge.net/projects/scid/ for issue, bug reports and discussions.
