### ISSUE TITLE
ECO table is not loading?

### ISSUE THREAD

**Issue by ksylvan** [benini/scid#185]
I tried to use the Database->Maintenance->ECO Clasify Games

and got this:

![image](https://github.com/user-attachments/assets/063bfc4e-7423-42bc-90a1-b50d336cb163)

The text in int Scid->About Scid is produced below:

```text
Scid: Shane's chess information database

Version 5.0.2, Feb  8 2024
Copyright (C) 1999-2004 Shane Hudson
Copyright (C) 2006-2009 Pascal Georges
Copyright (C) 2008-2011 Alexander Wagner
Copyright (C) 2011 Gerd Lorscheid
Copyright (C) 2009-2023 Fulvio Benini

Scid is licenced under the
GNU General Public License.


Using Tcl/Tk version: 8.6.13
Loaded packages:
Tcl(8.6.13),  TclOO(1.1.0),  Tk(8.6.13),  Ttk(8.6.13),  ezsmtp(1.0.0),  msgcat(1.6.1),  opt(0.4.8),  tcl::tommath(8.6.13),  tooltip(1.4.6),  ttk::theme::alt(8.6),  ttk::theme::aqua(8.6),  ttk::theme::clam(8.6),  ttk::theme::classic(8.6),  ttk::theme::default(8.6),  zlib(2.0.1).
```

And there seems to be no Load ECO File action in any of the submenus.

**Comment by ukscid** [comment]
You have to load a eco file.
You can select a eco file: Options -> Resources...
Maybe you have removed the eco file. SCID does not throw a error, if a eco file could not load at start.
You can download a eco file from [here](https://sourceforge.net/p/scid/code/ci/master/tree/scid.eco).

**Comment by benini** [comment]
Use https://sourceforge.net/projects/scid/ for issue, bug reports and discussions.
