### ISSUE TITLE
Scrambled Compressed Rows in submenus (e.g. preferences) and problems enlarging board

### ISSUE THREAD

**Issue by Willogically** [benini/scid#190]
I have problems with compressed rows, making it difficult to read any text in submenus. Is there a way to fix this -see example in attachment. Also is there a way to make the board bigger -it's on maximum size in the added attachement, but I want it to fill the screen at least top down -also posted on Sourcefourge [https://sourceforge.net/p/scid/wiki/StartHere/].
![Screenshot SCID](https://github.com/user-attachments/assets/88c54521-ea4f-4a0c-b122-40eb64358d29)

**Comment by benini** [comment]
Duplicate of:
https://sourceforge.net/p/scid/bugs/242/
