### ISSUE TITLE
Fold/unfold variations in pgn window

### ISSUE THREAD

**Issue by ukscid** [benini/scid#191]
Feature: The opportunity to unfold/fold variations in the pgn window:

```
1.d4 d5 2.c4 c6 [+] 3.Nf3 Nf6 *
1.d4 d5 2.c4 c6 [-] ( 2...e6 3.Nc3 c6 ) 3.Nf3 Nf6 * 
```

Clicking on [+] unfolds the variation, [-] folds the variation.
via popup menu it is possible to fold/unfold all variations at once

**Comment by benini** [comment]
**DO NOT OPEN ISSUES HERE!**

Use Sourceforge, it's a mess to have tickets in two repositories that have to be synchronize, with potential duplicates, etc...
