### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by rolandlo** [benini/scid#96]
Hi Scid devs!

Great that Scid is actively developed further. Thanks for all your work!
In view of the growing popularity of flatpaks, I would love to see Scid distributed as a flatpak on [Flathub](https://flathub.org) . This is a central place, from which users of all kind of Linux distributions can get their apps either by installing through command line or in a graphical way through the app center of the distribution.

I just built a flatpak out of Scid v4.8.0 and it was really easy (having prior experience with other flatpaks), even bundling Stockfish and Lc0 went pretty smoothly. In case you are interested I could share the flatpak manifest and create a PR. 
Submission on Flathub is pretty straightforward, see https://github.com/flathub/flathub/wiki/App-Submission, so I think this would be a great and painless way to increase the popularity of Scid.

A question on the side: Is this the right place to make this suggestion or should I head to the sourceforge repo?

**Comment by benini** [comment]
Hi,
I don't know flatpak, but it seems great, please go on!

This is the right place for pull requests. Sourceforge is the official repository for code and file releases, but github have better integration with CI tools.
